### ISSUE TITLE
Appwrite template _APP_DOMAIN_TARGET generating as "domain.com_TARGET"

### ISSUE THREAD

**Issue by McPizzaIs** [coollabsio/coolify-community-templates#11]
Ran into an issue when trying to use the _APP_DOMAIN_TARGET

By viewing the loaded env in the docker container, I see that  the variable is being loaded as `_APP_DOMAIN_TARGET=XXXXX_target` where XXXXX is the domain... so theres an extra `"_target"` set in the string

Not sure where this is coming from

In the template there are two variables being set:
`_APP_DOMAIN=$$config__app_domain`
` _APP_DOMAIN_TARGET=$$config__app_domain_target`

Could it be that its using the value of `$$config__app_domain` and somehow appending the `_target` there, rather than using the full name variable?
Perhaps an issue saving the full variable name to the DB causing it to pick up the incorrect one?

**Comment by andrasbacsai** [comment]
It is an issue in Coolify, I had a small typo in how I parse templates - which was fixed in [v3.11.11](https://github.com/coollabsio/coolify/releases/tag/v3.11.11).

Sorry about it!
