### ISSUE TITLE
Appwrite functions consistently failing to deploy

### ISSUE THREAD

**Issue by michachan** [coollabsio/coolify-community-templates#16]
Expected Behavior: When deploying a function on Appwrite, deployed functions should be able to be built
Actual Behavior: When deploying a function on an appwrite instance, builds will consistently fail
Appwrite versions: all

Additional info: Appwrite compose should have a /tmp rw mount, but is not reflected in the Appwrite community template

> 2022-12-12T04:07:33.734135807Z Successfully Warmed up Node.js 18.0!
> 2022-12-12T04:07:33.744381301Z Successfully Warmed up Node.js 16.0!
> 2022-12-12T04:09:24.345246668Z Building container : project-6396a9743a3e635a81e3
> 2022-12-12T04:09:24.860534026Z
> 2022-12-12T04:09:24.860500763Z Build failed: Docker Error: tar: can't open '/tmp/code.tar.gz': No such file or directory
> 2022-12-12T04:09:25.199422990Z [Error] Type: Exception
> 2022-12-12T04:09:25.200244681Z [Error] Line: 353
> 2022-12-12T04:09:25.200183805Z [Error] File: /usr/src/code/app/executor.php
> 2022-12-12T04:09:25.200153969Z
> 2022-12-12T04:09:25.200148147Z [Error] Message: Docker Error: tar: can't open '/tmp/code.tar.gz': No such file or directory
> 2022-12-12T05:03:39.324789542Z Building container : project-6396b62b34554376e646
> 2022-12-12T05:03:39.891231749Z
> 2022-12-12T05:03:39.891205409Z Build failed: Docker Error: tar: can't open '/tmp/code.tar.gz': No such file or directory
> 2022-12-12T05:03:40.222271700Z [Error] Line: 353
> 2022-12-12T05:03:40.222269626Z [Error] File: /usr/src/code/app/executor.php
> 2022-12-12T05:03:40.222267252Z
> 2022-12-12T05:03:40.222264016Z [Error] Message: Docker Error: tar: can't open '/tmp/code.tar.gz': No such file or directory
> 2022-12-12T05:03:40.222240963Z [Error] Type: Exception
> 2022-12-12T05:07:33.612679768Z Running maintenance task ...
> 2022-12-12T06:07:33.611870614Z Running maintenance task ...

**Comment by andrasbacsai** [comment]
I've updated the community templates with the right `/tmp` permissions. 

One of the users already confirmed that it's working. Can you also please recheck? You need to stop/start Appwrite service.

**Comment by michachan** [comment]
Resolved, thanks!
