### ISSUE TITLE
Ghost is incompatible with MariaDB

### ISSUE THREAD

**Issue by kevinansfield** [coollabsio/coolify-community-templates#2]
Hey! 👋 Thanks for all the effort you're putting into Coolify, looks like a really useful service 😊

I just wanted to add a note about the Ghost template with MariaDB because it may result in users ending up in difficult situations. Ghost since version 5 only officially supports MySQL 8. MariaDB has _sometimes_ worked in the past but we've had multiple instances recently where migrations or other functionality has been broken bringing sites down when they try to upgrade, with the only official fix to migrate from MariaDB to MySQL.

Didn't want to open a PR just deleting the template because I don't know how that would affect anyone already using it so thought I'd open the discussion first 🙂

**Comment by andrasbacsai** [comment]
Thanks for the suggestion!

The MariaDB version of Ghost is still in the templates (backward compatibility), but no one could install it. 
Added a MySQL-based one as the default. 🙂
