### ISSUE TITLE
Ghost versions outdated

### ISSUE THREAD

**Issue by LittleBigFrog** [coollabsio/coolify-community-templates#42]
Latest vesrion available in coolify is 5.44 (april 2022).

Should we add images 5 and latest ?

service-tags.json
https://hub.docker.com/r/bitnami/ghost/tags

also wondering why coolify uses bitnami instead of official docker https://hub.docker.com/_/ghost ?

Thanks

**Comment by siriokun** [comment]
In this commit https://github.com/siriokun/coolify-community-templates/commit/24e8d4dba32adf374aeac93743908092dce435c0 comes with following:

- Update Ghost with latest and alpine version
- Use only official Ghost image
- Remove Ghost MariaDB template

From Ghost 5, supported database is MySQL (Production) and SQLite 3 (Development). See https://ghost.org/docs/faq/supported-databases/

**Comment by siriokun** [comment]
Need your review on this @andrasbacsai

**Comment by LittleBigFrog** [comment]
@siriokun 
Great using official ghost image.
however, will email secrets still function?
Previously, we had to use the following secrets:
mail__options__secureConnection
mail__options__port
mail__options__auth__pass
mail__options__auth__user
mail__options__host
mail__options__from
mail__transport

**Comment by andrasbacsai** [comment]
I've updated the Ghost versions. Btw, you can use custom docker image tags as well, not just the predefined ones.
![image](https://github.com/coollabsio/coolify-community-templates/assets/5845193/be84c02e-85d4-417b-b9d5-b64aac722592)

I would not like to change the base docker image in v3, as it could make a lot of weird things on the existing Ghost instances.

In v4, I will redefine how service are working, so it would be much much better.
